name: Sync to Organization

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Używamy domyślnego tokena do pobrania kodu
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Push to PPCFT
        run: |
          # Tutaj używamy Twojego SYNC_TOKEN do wysyłki
          git remote add destination https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/PPCFT/GenTab.git
          git fetch origin main
          git push destination HEAD:main --force --tags
